name: CI
on: [push, pull_request]
jobs:
  build:
    name: Test on Ruby ${{ matrix.ruby_version }}, Rails ${{ matrix.rails_version }}, graphql-ruby ${{ matrix.graphql_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
        graphql_version:
          - "~> 1.13.0"
          - "~> 2.0.0"
          - "~> 2.1.0"
          - "~> 2.2.0"
        rails_version:
          - "~> 5.2.0"
          - "~> 6.0.0"
          - "~> 6.1.0"
          - "~> 7.0.0"
          - "~> 7.1.0"
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Set up Ruby ${{ matrix.ruby_version }}
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: Build and test
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec rake test
        env:
          RAILS_VERSION: ${{ matrix.rails_version }}
          GRAPHQL_VERSION: ${{ matrix.graphql_version }}
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1
        with:
          ruby-version: 3.2
      - name: Build and test
        run: |-
          bundle install --jobs 4 --retry 3
          bundle exec rake rubocop
