name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  release:
    name: Release to RubyGems
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1
        with:
          bundler-cache: true
          ruby-version: ruby
      - uses: rubygems/release-gem@612653d273a73bdae1df8453e090060bb4db5f31 # v1
